# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consensus_node/raft.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'consensus_node/raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63onsensus_node/raft.proto\x12\x04raft\"K\n\x08LogEntry\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\r\n\x05index\x18\x03 \x01(\x03\x12\x11\n\tclient_id\x18\x04 \x01(\t\"g\n\x12RequestVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x03\x12\x15\n\rlast_log_term\x18\x04 \x01(\x03\"K\n\x13RequestVoteResponse\x12\x14\n\x0cvote_granted\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x10\n\x08voter_id\x18\x03 \x01(\t\"n\n\x14\x41ppendEntriesRequest\x12\x11\n\tleader_id\x18\x01 \x01(\t\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\x03\"\\\n\x15\x41ppendEntriesResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04term\x18\x02 \x01(\x03\x12\x0f\n\x07node_id\x18\x03 \x01(\t\x12\x13\n\x0bmatch_index\x18\x04 \x01(\x03\"3\n\rClientRequest\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x11\n\tclient_id\x18\x02 \x01(\t\"U\n\x0e\x43lientResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\r\n\x05index\x18\x04 \x01(\x03\x32\xd7\x01\n\x0bRaftService\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12:\n\rClientCommand\x12\x13.raft.ClientRequest\x1a\x14.raft.ClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consensus_node.raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LOGENTRY']._serialized_start=35
  _globals['_LOGENTRY']._serialized_end=110
  _globals['_REQUESTVOTEREQUEST']._serialized_start=112
  _globals['_REQUESTVOTEREQUEST']._serialized_end=215
  _globals['_REQUESTVOTERESPONSE']._serialized_start=217
  _globals['_REQUESTVOTERESPONSE']._serialized_end=292
  _globals['_APPENDENTRIESREQUEST']._serialized_start=294
  _globals['_APPENDENTRIESREQUEST']._serialized_end=404
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=406
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=498
  _globals['_CLIENTREQUEST']._serialized_start=500
  _globals['_CLIENTREQUEST']._serialized_end=551
  _globals['_CLIENTRESPONSE']._serialized_start=553
  _globals['_CLIENTRESPONSE']._serialized_end=638
  _globals['_RAFTSERVICE']._serialized_start=641
  _globals['_RAFTSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
