# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: consensus_node/two_phase.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'consensus_node/two_phase.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63onsensus_node/two_phase.proto\x12\x05twopc\"(\n\nTxnRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"V\n\tTxnResult\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t\x12\x0e\n\x06txn_id\x18\x04 \x01(\t\"Q\n\x0bVoteRequest\x12\x0e\n\x06txn_id\x18\x01 \x01(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x04 \x01(\t\"D\n\x0cVoteResponse\x12\x13\n\x0bvote_commit\x18\x01 \x01(\x08\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"l\n\x0f\x44\x65\x63isionRequest\x12\x0e\n\x06txn_id\x18\x01 \x01(\t\x12\x15\n\rglobal_commit\x18\x02 \x01(\x08\x12\x0b\n\x03key\x18\x03 \x01(\t\x12\r\n\x05value\x18\x04 \x01(\t\x12\x16\n\x0e\x63oordinator_id\x18\x05 \x01(\t\"/\n\x0b\x44\x65\x63isionAck\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0f\n\x07\x61pplied\x18\x02 \x01(\x08\x32\xb3\x01\n\x0fTwoPhaseService\x12\x37\n\x10StartTransaction\x12\x11.twopc.TxnRequest\x1a\x10.twopc.TxnResult\x12/\n\x04Vote\x12\x12.twopc.VoteRequest\x1a\x13.twopc.VoteResponse\x12\x36\n\x08\x44\x65\x63ision\x12\x16.twopc.DecisionRequest\x1a\x12.twopc.DecisionAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consensus_node.two_phase_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TXNREQUEST']._serialized_start=41
  _globals['_TXNREQUEST']._serialized_end=81
  _globals['_TXNRESULT']._serialized_start=83
  _globals['_TXNRESULT']._serialized_end=169
  _globals['_VOTEREQUEST']._serialized_start=171
  _globals['_VOTEREQUEST']._serialized_end=252
  _globals['_VOTERESPONSE']._serialized_start=254
  _globals['_VOTERESPONSE']._serialized_end=322
  _globals['_DECISIONREQUEST']._serialized_start=324
  _globals['_DECISIONREQUEST']._serialized_end=432
  _globals['_DECISIONACK']._serialized_start=434
  _globals['_DECISIONACK']._serialized_end=481
  _globals['_TWOPHASESERVICE']._serialized_start=484
  _globals['_TWOPHASESERVICE']._serialized_end=663
# @@protoc_insertion_point(module_scope)
