# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from consensus_node import two_phase_pb2 as consensus__node_dot_two__phase__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in consensus_node/two_phase_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoPhaseServiceStub(object):
    """Two-phase commit service used for both the voting and decision phases.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTransaction = channel.unary_unary(
                '/twopc.TwoPhaseService/StartTransaction',
                request_serializer=consensus__node_dot_two__phase__pb2.TxnRequest.SerializeToString,
                response_deserializer=consensus__node_dot_two__phase__pb2.TxnResult.FromString,
                _registered_method=True)
        self.Vote = channel.unary_unary(
                '/twopc.TwoPhaseService/Vote',
                request_serializer=consensus__node_dot_two__phase__pb2.VoteRequest.SerializeToString,
                response_deserializer=consensus__node_dot_two__phase__pb2.VoteResponse.FromString,
                _registered_method=True)
        self.Decision = channel.unary_unary(
                '/twopc.TwoPhaseService/Decision',
                request_serializer=consensus__node_dot_two__phase__pb2.DecisionRequest.SerializeToString,
                response_deserializer=consensus__node_dot_two__phase__pb2.DecisionAck.FromString,
                _registered_method=True)


class TwoPhaseServiceServicer(object):
    """Two-phase commit service used for both the voting and decision phases.
    """

    def StartTransaction(self, request, context):
        """Client entry point to start a transaction on the coordinator.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Vote(self, request, context):
        """Phase 1: coordinator -> participants to collect votes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Decision(self, request, context):
        """Phase 2: coordinator -> participants to announce decision.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoPhaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTransaction': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTransaction,
                    request_deserializer=consensus__node_dot_two__phase__pb2.TxnRequest.FromString,
                    response_serializer=consensus__node_dot_two__phase__pb2.TxnResult.SerializeToString,
            ),
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=consensus__node_dot_two__phase__pb2.VoteRequest.FromString,
                    response_serializer=consensus__node_dot_two__phase__pb2.VoteResponse.SerializeToString,
            ),
            'Decision': grpc.unary_unary_rpc_method_handler(
                    servicer.Decision,
                    request_deserializer=consensus__node_dot_two__phase__pb2.DecisionRequest.FromString,
                    response_serializer=consensus__node_dot_two__phase__pb2.DecisionAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'twopc.TwoPhaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('twopc.TwoPhaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoPhaseService(object):
    """Two-phase commit service used for both the voting and decision phases.
    """

    @staticmethod
    def StartTransaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseService/StartTransaction',
            consensus__node_dot_two__phase__pb2.TxnRequest.SerializeToString,
            consensus__node_dot_two__phase__pb2.TxnResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseService/Vote',
            consensus__node_dot_two__phase__pb2.VoteRequest.SerializeToString,
            consensus__node_dot_two__phase__pb2.VoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Decision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/twopc.TwoPhaseService/Decision',
            consensus__node_dot_two__phase__pb2.DecisionRequest.SerializeToString,
            consensus__node_dot_two__phase__pb2.DecisionAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
