# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: picture.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpicture.proto\"/\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"/\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04node\x18\x02 \x01(\t\"!\n\rSearchRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"<\n\x0eSearchResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\r\n\x05likes\x18\x03 \x01(\x05\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"/\n\x10\x44ownloadResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\r\n\x05\x66ound\x18\x02 \x01(\x08\"!\n\rDeleteRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"!\n\x0e\x44\x65leteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1f\n\x0bLikeRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\".\n\x0cLikeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05likes\x18\x02 \x01(\x05\"\r\n\x0bListRequest\"\x80\x01\n\x0cListResponse\x12-\n\x08pictures\x18\x01 \x03(\x0b\x32\x1b.ListResponse.PicturesEntry\x1a\x41\n\rPicturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.PictureMetadata:\x02\x38\x01\".\n\x0fPictureMetadata\x12\r\n\x05likes\x18\x01 \x01(\x05\x12\x0c\n\x04node\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\".\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04node\x18\x02 \x01(\t2\xb7\x02\n\x0ePictureService\x12)\n\x06Upload\x12\x0e.UploadRequest\x1a\x0f.UploadResponse\x12)\n\x06Search\x12\x0e.SearchRequest\x1a\x0f.SearchResponse\x12/\n\x08\x44ownload\x12\x10.DownloadRequest\x1a\x11.DownloadResponse\x12)\n\x06\x44\x65lete\x12\x0e.DeleteRequest\x1a\x0f.DeleteResponse\x12#\n\x04Like\x12\x0c.LikeRequest\x1a\r.LikeResponse\x12#\n\x04List\x12\x0c.ListRequest\x1a\r.ListResponse\x12)\n\x06Health\x12\x0e.HealthRequest\x1a\x0f.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'picture_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LISTRESPONSE_PICTURESENTRY']._options = None
  _globals['_LISTRESPONSE_PICTURESENTRY']._serialized_options = b'8\001'
  _globals['_UPLOADREQUEST']._serialized_start=17
  _globals['_UPLOADREQUEST']._serialized_end=64
  _globals['_UPLOADRESPONSE']._serialized_start=66
  _globals['_UPLOADRESPONSE']._serialized_end=113
  _globals['_SEARCHREQUEST']._serialized_start=115
  _globals['_SEARCHREQUEST']._serialized_end=148
  _globals['_SEARCHRESPONSE']._serialized_start=150
  _globals['_SEARCHRESPONSE']._serialized_end=210
  _globals['_DOWNLOADREQUEST']._serialized_start=212
  _globals['_DOWNLOADREQUEST']._serialized_end=247
  _globals['_DOWNLOADRESPONSE']._serialized_start=249
  _globals['_DOWNLOADRESPONSE']._serialized_end=296
  _globals['_DELETEREQUEST']._serialized_start=298
  _globals['_DELETEREQUEST']._serialized_end=331
  _globals['_DELETERESPONSE']._serialized_start=333
  _globals['_DELETERESPONSE']._serialized_end=366
  _globals['_LIKEREQUEST']._serialized_start=368
  _globals['_LIKEREQUEST']._serialized_end=399
  _globals['_LIKERESPONSE']._serialized_start=401
  _globals['_LIKERESPONSE']._serialized_end=447
  _globals['_LISTREQUEST']._serialized_start=449
  _globals['_LISTREQUEST']._serialized_end=462
  _globals['_LISTRESPONSE']._serialized_start=465
  _globals['_LISTRESPONSE']._serialized_end=593
  _globals['_LISTRESPONSE_PICTURESENTRY']._serialized_start=528
  _globals['_LISTRESPONSE_PICTURESENTRY']._serialized_end=593
  _globals['_PICTUREMETADATA']._serialized_start=595
  _globals['_PICTUREMETADATA']._serialized_end=641
  _globals['_HEALTHREQUEST']._serialized_start=643
  _globals['_HEALTHREQUEST']._serialized_end=658
  _globals['_HEALTHRESPONSE']._serialized_start=660
  _globals['_HEALTHRESPONSE']._serialized_end=706
  _globals['_PICTURESERVICE']._serialized_start=709
  _globals['_PICTURESERVICE']._serialized_end=1020
# @@protoc_insertion_point(module_scope)
